"""Added priority, tags, notes, assigned_to to Incident

Revision ID: 2b7b8c9d9c6d
Revises: 0a93556466ff
Create Date: 2025-07-19 13:12:03.158758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7b8c9d9c6d'
down_revision = '0a93556466ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('tags')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
